# Generated by Django 5.1.3 on 2025-01-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_users_remove_books_url_image_alter_books_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.users'),
        ),
    ]
