on: [push]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t babe051/mini_projet_django:latest .

      - name: push image to docker hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u babe051 --password-stdin
          docker push babe051/mini_projet_django:latest
